# Generated by Django 3.1.2 on 2020-11-13 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201113_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoptionchoice',
            old_name='is_available',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='productoptionchoice',
            old_name='is_default',
            new_name='default',
        ),
    ]
