# Generated by Django 3.1.2 on 2020-11-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20201101_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproduct',
            name='chosen_options',
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='chosen_options',
            field=models.ManyToManyField(blank=True, related_name='ordered_products', to='common.ProductOptionChoice'),
        ),
    ]
