# Generated by Django 3.1.2 on 2020-11-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20201101_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
