# Generated by Django 3.1.2 on 2020-11-04 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20201103_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.CharField(default=0, max_length=16, verbose_name='Номер заказа'),
        ),
        migrations.CreateModel(
            name='CafeRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(choices=[(1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0)], decimal_places=1, max_digits=2)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='common.cafe')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='common.consumer')),
            ],
        ),
    ]
