# Generated by Django 3.1.2 on 2020-11-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20201104_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='rating',
        ),
        migrations.AddField(
            model_name='cafe',
            name='average_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caferating',
            name='value',
            field=models.FloatField(choices=[(1.0, 1.0), (1.5, 1.5), (2.0, 2.0), (2.5, 2.5), (3.0, 3.0), (3.5, 3.5), (4.0, 4.0), (4.5, 4.5), (5.0, 5.0)]),
        ),
    ]
