# Generated by Django 3.1.2 on 2020-11-10 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20201110_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cafe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='common.cafe'),
            preserve_default=False,
        ),
    ]
