# Generated by Django 3.1.2 on 2020-11-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_order_cafe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='done_at',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='finished_at',
            new_name='ready_at',
        ),
    ]
