# Generated by Django 3.1.2 on 2020-11-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_available',
            new_name='available',
        ),
        migrations.AlterField(
            model_name='cafe',
            name='registration_code',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
