# Generated by Django 3.1.2 on 2020-11-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20201101_1212'),
        ('accounts', '0002_auto_20201027_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consumer',
        ),
    ]
